name: "bge"
backend: "python"
max_batch_size: 512

input [
  { name: "TEXT" data_type: TYPE_STRING dims: [ -1 ] }
]

output [
  { name: "dense_vecs" data_type: TYPE_FP16 dims: [ -1 ] }
]

instance_group [
  { kind: KIND_GPU, gpus: [0] }
]

dynamic_batching {
  preferred_batch_size: [1,8, 64, 256, 512]
}
